version: '3.8'

networks:
  backend-network:
    driver: bridge
  proxy-network:
    driver: bridge

services:
  app:
    container_name: app-server
    image: nextcloud:30-fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    networks:
      - backend-network

  nextcloud-cron:
    image: nextcloud:30-fpm
    restart: unless-stopped
    depends_on:
      - app
    entrypoint: /cron.sh
    volumes:
      - app_data:/var/www/html
    networks:
      - backend-network
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: h4rdl/doc_server
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    networks:
      - backend-network
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    expose:
      - '80'
      - '443'
    networks:
      - backend-network
    volumes:
      - ./cert:/etc/nginx/cert
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      - "81:81"       # веб-панель NPM
      - "8443:443"
    environment:
      - TZ=${TZ}
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
      - backend-network
  db:
    container_name: nextcloud_db
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    restart: always
    networks:
      - backend-network
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
  npm_data:
  npm_letsencrypt:
